events {}

http {
    server {
        listen 10000;

        location /sky4.m3u8 {
            proxy_pass https://ava.karmakurama.com/dokko1/premium591/mono.m3u8;
            proxy_set_header Referer "https://ava.karmakurama.com/premium.php?id=591";
            proxy_set_header User-Agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0";
        }

        location /sky3.m3u8 {
            proxy_pass https://ava.karmakurama.com/dokko1/premium590/mono.m3u8;
            proxy_set_header Referer "https://ava.karmakurama.com/premium.php?id=590";
            proxy_set_header User-Agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0";
        }

        location /sky2.m3u8 {
            proxy_pass https://ava.karmakurama.com/dokko1/premium589/mono.m3u8;
            proxy_set_header Referer "https://ava.karmakurama.com/premium.php?id=589";
            proxy_set_header User-Agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0";
        }

        location /sky1.m3u8 {
            proxy_pass https://ava.karmakurama.com/dokko1/premium588/mono.m3u8;
            proxy_set_header Referer "https://ava.karmakurama.com/premium.php?id=588";
            proxy_set_header User-Agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0";
        }
    }
}
